apiVersion: v1
kind: Service
metadata:
  name: swift-server
  labels:
    app: swift-server
spec:
  type: LoadBalancer
  selector:
    app: swift-server
  ports:
  - name: tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift-server
  labels:
    app: swift-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swift-server
  template:
    metadata:
      labels:
        app: swift-server
    spec:
      containers:
      - name: swift-server
        image: antonioberben/swift-server:0.9.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: swift-client
#   labels:
#     app: swift-client
# spec:
#   selector:
#     app: swift-client
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: swift-client
#   labels:
#     app: swift-client
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: swift-client
#   template:
#     metadata:
#       labels:
#         app: swift-client
#     spec:
#       containers:
#       - name: swift-client
#         image: antonioberben/xmlrpc-client:0.9.0
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 9090
#         env:
#         - name: "SERVER_HOST"
#           value: "swift-server.demo.svc.cluster.local"
