apiVersion: v1
kind: Service
metadata:
  name: xmlrpc-server
  labels:
    app: xmlrpc-server
spec:
  type: LoadBalancer
  selector:
    app: xmlrpc-server
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmlrpc-server
  labels:
    app: xmlrpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmlrpc-server
  template:
    metadata:
      labels:
        app: xmlrpc-server
    spec:
      containers:
      - name: xmlrpc-server
        image: antonioberben/xmlrpc-server:0.9.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: xmlrpc-client
#   labels:
#     app: xmlrpc-client
# spec:
#   selector:
#     app: xmlrpc-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmlrpc-client
  labels:
    app: xmlrpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmlrpc-client
  template:
    metadata:
      labels:
        app: xmlrpc-client
    spec:
      containers:
      - name: xmlrpc-client
        image: antonioberben/xmlrpc-client:0.9.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        - name: "SERVER_HOST"
          value: "xmlrpc-server.demo.svc.cluster.local"
